#!/usr/bin/env python3
"""Portable Learning OS control plane. Markdown is authoritative.

Adapted from the author's personal runtime; no session ingestion or daemon.
Run this copy only inside a workspace generated by init_workspace.py.
"""
from __future__ import annotations
import argparse
import difflib
import hashlib
import json
import os
import re
import sys
import tempfile
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SUBJECTS = ROOT / '科目'
PREFERENCES = ROOT / '学习偏好.md'
SECTIONS = ['当前进度', '我喜欢的学习方式', '资料入口', '最近形成的理解', '接下来可以做什么']
NODE_TYPES = {'manager', 'leaf'}
EVIDENCE_KINDS = {'module_handoff', 'practice_attempt'}

def atomic_write(path: Path, text: str) -> None:
    if not path.resolve().is_relative_to(ROOT):
        raise ValueError('Write target escapes this private workspace.')
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temp_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    temp = Path(temp_name)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(text)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temp, path)
    finally:
        if temp.exists():
            temp.unlink()

def subjects() -> list[Path]:
    result = []
    for current, dirs, files in os.walk(SUBJECTS):
        dirs[:] = [d for d in dirs if not (Path(current)/d).is_symlink() and d not in {'资料', '模块', '学习记录', '练习', 'Anki', '总管归档', '.git', '__pycache__'}]
        if '学习主页.md' in files and 'AGENTS.md' in files and not any((Path(current)/f).is_symlink() for f in ('学习主页.md','AGENTS.md')):
            result.append(Path(current))
    return sorted(result)

def subject_label(subject: Path) -> str:
    return str(subject.relative_to(SUBJECTS))

def page(subject: Path) -> str:
    return (subject / "学习主页.md").read_text(encoding="utf-8")

def leaf_subject_for_cwd(cwd: str | None = None) -> Path | None:
    current = Path(cwd or os.getcwd()).resolve()
    try:
        current.relative_to(SUBJECTS.resolve())
    except ValueError:
        return None
    for candidate in [current, *current.parents]:
        if (candidate / 'AGENTS.md').exists() and (candidate / '学习主页.md').exists():
            return candidate if node_type(page(candidate)) == 'leaf' else None
        if candidate == SUBJECTS.resolve():
            break
    return None

def continuation_files(subject: Path) -> list[Path]:
    """Only curated bookmarks; automatic excerpt experiment is paused."""
    position = subject / '续学位置.md'
    return [position] if position.exists() else []

def position_text(subject: Path) -> str:
    sources = continuation_files(subject)
    if any(p.name == '自动续学片段.md' for p in sources):
        return '有自动对话片段，学习位置待核对（不等于已掌握）'
    position = subject / "续学位置.md"
    if not position.exists():
        return "未同步"
    text = position.read_text(encoding="utf-8").strip()
    closed = bool(re.search(r'^phase: closed\s*$', text, re.M))
    text = re.sub(r'\A---\s*\n.*?\n---\s*\n', '', text, flags=re.S)
    text = '\n'.join(line for line in text.splitlines() if not line.startswith(('#', '保存时间：', '当前模块：')))
    return ('已收尾｜' if closed else '') + first_nonempty_line(text) if text.strip() else "未同步"

def first_nonempty_line(text: str) -> str:
    return next((line.strip("- ") for line in text.splitlines() if line.strip()), "未同步")

def clip(text: str, limit: int) -> str:
    text = " ".join(text.split())
    return text if len(text) <= limit else text[: limit - 1].rstrip() + "…"

def node_type(text: str) -> str | None:
    match = re.search(r"^node_type:\s*(manager|leaf)\s*$", text, re.M)
    return match.group(1) if match else None

def node_role(subject: Path, all_subjects: list[Path] | None = None) -> str:
    explicit = node_type(page(subject))
    if explicit in NODE_TYPES:
        return explicit
    candidates = all_subjects if all_subjects is not None else subjects()
    prefix = subject.relative_to(SUBJECTS)
    if any(other != subject and prefix in other.relative_to(SUBJECTS).parents for other in candidates):
        return "manager"
    return "leaf"

def relative_subject(path_text: str) -> Path | None:
    candidate = (SUBJECTS / path_text).resolve()
    try:
        candidate.relative_to(SUBJECTS.resolve())
    except ValueError:
        return None
    return candidate

def section(text: str, heading: str) -> str:
    match = re.search(
        rf"^## {re.escape(heading)}(?:（[^）]*）|\([^)]*\))?\s*$\n(.*?)(?=^##\s|\Z)",
        text,
        re.M | re.S,
    )
    return match.group(1).strip() if match else ""

def first_line(text: str, heading: str) -> str:
    return next((line.strip().lstrip("- ") for line in section(text, heading).splitlines() if line.strip()), "暂无")

def score(query: str, candidate: str) -> float:
    norm = lambda value: "".join(char for char in value.casefold() if char.isalnum())
    q, c = norm(query), norm(candidate)
    if q == c:
        return 1.0
    if q in c or c in q:
        return 0.9
    return difflib.SequenceMatcher(None, q, c).ratio()

def aliases(text: str) -> list[str]:
    match = re.search(r"^aliases:\s*\[(.*?)\]\s*$", text, re.M)
    if not match:
        return []
    return [item.strip().strip('"\'') for item in match.group(1).split(",") if item.strip()]

def broken_local_links(path: Path) -> list[str]:
    """Check ordinary Markdown links while ignoring URLs and page anchors."""
    try:
        text = path.read_text(encoding='utf-8')
    except (OSError, UnicodeError):
        return []
    broken = []
    for match in re.finditer(r'\[[^\]]*\]\((<[^>]+>|[^)]+)\)', text):
        raw = match.group(1).strip()
        target = raw[1:-1] if raw.startswith('<') and raw.endswith('>') else raw.split()[0]
        target = target.split('#', 1)[0]
        if not target or re.match(r'^[a-zA-Z][a-zA-Z0-9+.-]*:', target):
            continue
        resolved = Path(target) if target.startswith('/') else path.parent / target
        if not resolved.exists():
            broken.append(raw)
    return broken

def heading_slugs(path: Path) -> set[str]:
    """GitHub 风格的标题锚点：去标点、空格转连字符；重复标题不追加序号（本库标题不重复）。"""
    try:
        text = path.read_text(encoding='utf-8')
    except (OSError, UnicodeError):
        return set()
    slugs = set()
    in_code = False
    for line in text.splitlines():
        if line.startswith('```'):
            in_code = not in_code
        match = re.match(r'^#{1,6}\s+(.*?)\s*#*\s*$', line)
        if match and not in_code:
            title = re.sub(r'[`*_]', '', match.group(1)).strip().lower()
            slugs.add(re.sub(r'\s+', '-', re.sub(r'[^\w\- ]', '', title, flags=re.UNICODE)))
    return slugs

def broken_anchors(path: Path, only_targets: set[Path] | None = None) -> list[str]:
    """检查指向 Markdown 文件的 #锚点是否对应真实标题；only_targets 限定被检查的目标文件。"""
    try:
        text = path.read_text(encoding='utf-8')
    except (OSError, UnicodeError):
        return []
    broken = []
    for match in re.finditer(r'\[[^\]]*\]\((<[^>]+>|[^)]+)\)', text):
        raw = match.group(1).strip()
        target = raw[1:-1] if raw.startswith('<') and raw.endswith('>') else raw.split()[0]
        if '#' not in target or re.match(r'^[a-zA-Z][a-zA-Z0-9+.-]*:', target):
            continue
        file_part, anchor = target.split('#', 1)
        resolved = path if not file_part else (Path(file_part) if file_part.startswith('/') else path.parent / file_part)
        if not resolved.resolve().is_relative_to(ROOT) or not resolved.is_file() or resolved.suffix != '.md' or not anchor:
            continue
        if only_targets is not None and resolved.resolve() not in only_targets:
            continue
        if anchor.lower() not in heading_slugs(resolved):
            broken.append(raw)
    return broken

def resolve_candidates(query: str, *, threshold: float = 0.72) -> list[Path]:
    """Best-scoring nodes for a query, with ancestors of a tied descendant dropped.

    A manager that lists its own child as an alias scores exactly as high as that
    child (数学一 aliases 概率论). The child is the real learning entry, so an
    ancestor never wins a tie against its own descendant. Unrelated ties such as
    408/数据结构 vs 804/数据结构 stay ambiguous for the caller to report.
    """
    registered = subjects()
    exact = relative_subject(query)
    if exact in registered:
        return [exact]
    ranked = sorted(
        ((max(score(query, label) for label in [subject.name, subject_label(subject), *aliases(page(subject))]), subject)
         for subject in registered),
        key=lambda item: (-item[0], item[1].name),
    )
    if not ranked or ranked[0][0] < threshold:
        return []
    tied = [subject for value, subject in ranked if value == ranked[0][0]]
    return [s for s in tied if not any(other is not s and s in other.parents for other in tied)]

def resolve(query: str) -> Path | None:
    candidates = resolve_candidates(query)
    return candidates[0] if len(candidates) == 1 else None

def command_status(_: argparse.Namespace) -> int:
    items = subjects()
    print(f"Learning OS：{len(items)} 个已登记节点\n")
    for subject in items:
        text = page(subject)
        role = node_role(subject, items)
        label = "协调节点" if role == "manager" else "学习叶节点"
        print(f"## {subject_label(subject)} [{label}]")
        print(f"当前：{first_line(text, '当前进度')}")
        print(f"下一步：{first_line(text, '接下来可以做什么')}\n")
    print("这是完整注册表；分层总览请使用 overview [总管]。")
    return 0

def command_brief(args: argparse.Namespace) -> int:
    """Print a bounded control-plane overview without entering a course."""
    items = subjects()
    query = getattr(args, 'query', None)
    if query:
        chosen = resolve(query)
        if not chosen:
            print('未找到指定节点。'); return 1
        items = [chosen]
    output = ["# Learning OS 控制面总览", f"登记节点：{len(items)}；根节点只做审查、扩展和跨域总览，不承担教学。"]
    reads, chars = 0, 0
    stage = ROOT / "当前阶段.md"
    if stage.exists():
        stage_text = stage.read_text(encoding="utf-8")
        reads += 1; chars += len(stage_text)
        output.append(f"当前阶段：{clip(first_line(stage_text, '阶段判断'), 320)}")
        focus = first_line(stage_text, '当前方向关注')
        if focus != '暂无':
            output.append(f"方向关注：{clip(focus, 320)}")
    if query:
        shown = items
    else:
        shown = [p for p in items if nearest_registered_parent(p, items) is None]
        output.append("\n## 顶层数据域")
    allowance = min(260, max(120, (4200 - sum(len(subject_label(p)) + 35 for p in shown)) // max(1, len(shown))))
    for subject in shown:
        text = page(subject)
        role = "协调节点" if node_type(text) == "manager" else "学习叶节点"
        reads += 1; chars += len(text)
        line = clip(first_line(text, "当前进度"), allowance // 2)
        evidence = evidence_records(subject, recursive=node_type(text) == 'manager')
        evidence_note = f"；证据入口（需核正文） {len(evidence)} 条" if evidence else "；暂无结构化交接/作答证据"
        detail = f"- {subject_label(subject)} [{role}]：{line}{evidence_note}"
        if query and node_type(text) == 'leaf':
            position = position_text(subject)
            if position != '未同步':
                detail += f"；临时位置：{clip(position, allowance // 2)}"
        output.append(detail)
    catalog = ROOT / '数据层/catalog.sqlite3'
    if catalog.is_file() and not catalog.is_symlink():
        taken = datetime.fromtimestamp(catalog.stat().st_mtime, timezone.utc).isoformat()
        output.append(f'可选索引缓存：{taken}；按需用 tools/build_index.py --apply 重建，不能代替当前Markdown。')
    output.append("可用入口：overview [总管] 查看分层状态；guidance-context 准备方向分析；status 查看完整注册表。")
    output.append(f'概要来源正文规模（去重，不含节点识别/查询匹配）：{reads} 文件，{chars} 字符。只读概要，不代表对所有材料完成审计。')
    rendered = '\n'.join(output)
    if len(rendered) > 7900:
        rendered = '\n'.join(output[:3] + [f'- {subject_label(s)}' for s in items] + ['容量不足：仅列节点，请用 brief 科目名 展开。'])
    print(clip(rendered, 7999) if len(rendered) > 8000 else rendered)
    return 0

def snapshot_age_note(started_at: str, *, stale_days: int = 14) -> str:
    """Flag an index snapshot that is old enough to mislead; never blocks brief."""
    try:
        taken = datetime.fromisoformat(started_at)
    except (TypeError, ValueError):
        return ''
    now = datetime.now(taken.tzinfo or timezone.utc)
    days = (now - taken).days
    if days < stale_days:
        return ''
    return f'（已过期 {days} 天，重建：python3 数据层/统一索引/脚本/sync_learning_os.py）'

def tree_lines(items: list[Path]) -> list[str]:
    registered = {subject.relative_to(SUBJECTS): subject for subject in items}
    visible = set()
    for relative in registered:
        visible.update(Path(*relative.parts[:index]) for index in range(1, len(relative.parts) + 1))
    lines = []
    for relative in sorted(visible, key=lambda p: tuple(p.parts)):
        depth = len(relative.parts) - 1
        subject = registered.get(relative)
        label = node_role(subject, items) if subject else "category"
        lines.append(f"{'  ' * depth}- {relative.name} [{label}]")
    return lines

def nearest_registered_parent(subject: Path, items: list[Path]) -> Path | None:
    parents = [candidate for candidate in items if candidate != subject and candidate in subject.parents]
    return max(parents, key=lambda item: len(item.parts)) if parents else None

def metadata_value(text: str, key: str) -> str | None:
    match = re.search(rf"^{re.escape(key)}:\s*(.+?)\s*$", text, re.M)
    return match.group(1).strip().strip('"\'') if match else None

def frontmatter_block(text: str) -> str:
    """Return only the YAML frontmatter (between the leading and next '---' lines).

    Files without a leading '---' frontmatter block return ''. This keeps
    metadata_value from matching example `key: value` lines that merely
    appear in a file's body (e.g. a template showing what frontmatter looks
    like), which are not real evidence metadata.
    """
    if not text.startswith('---\n'):
        return ''
    end = text.find('\n---', 4)
    return text[:end] if end != -1 else ''

def evidence_records(subject: Path, recursive: bool = False) -> list[dict]:
    roots = [subject / '学习记录', subject / '练习']
    if recursive:
        roots = []
        for child in subjects():
            if child == subject or subject in child.parents:
                roots.extend([child / '学习记录', child / '练习'])
    records = []
    for root in roots:
        if not root.exists():
            continue
        for path in sorted(root.rglob('*.md')):
            if path.is_symlink() or not path.resolve().is_relative_to(ROOT):
                continue
            if path.name == 'README.md' or '自动续学' in path.parts:
                continue
            try:
                text = path.read_text(encoding='utf-8')
            except (OSError, UnicodeError):
                continue
            front = frontmatter_block(text)
            kind = metadata_value(front, 'kind')
            if kind not in EVIDENCE_KINDS:
                continue
            records.append({
                'kind': kind,
                'subject': metadata_value(front, 'subject') or subject_label(subject),
                'module': metadata_value(front, 'module') or '未标注模块',
                'occurred_at': metadata_value(front, 'occurred_at') or '时间未标注',
                'result': metadata_value(front, 'result') or '未标注结果',
                'path': path,
            })
    return records

def command_overview(args: argparse.Namespace) -> int:
    items = subjects()
    target = resolve(args.query) if args.query else None
    if args.query and not target:
        print('未找到指定节点。', file=sys.stderr); return 1
    if target and node_role(target, items) == 'leaf':
        shown = [target]
        title = subject_label(target)
    elif target:
        shown = [p for p in items if nearest_registered_parent(p, items) == target]
        title = subject_label(target)
    else:
        shown = [p for p in items if nearest_registered_parent(p, items) is None]
        title = '全局'
    print(f'# {title}｜分层学习状况\n')
    print('说明：主页是声明状态；只有带元数据的模块交接和真实作答计入证据入口（需核正文）。资料存在不等于学过。\n')
    for subject in shown:
        text = page(subject)
        role = 'manager' if node_type(text) == 'manager' else 'leaf'
        evidence = evidence_records(subject, recursive=node_type(text) == 'manager')
        print(f'## {subject_label(subject)} [{role}]')
        print(f"当前声明：{first_line(text, '当前进度')}")
        print(f"下一入口：{first_line(text, '接下来可以做什么')}")
        print(f"证据入口（需核正文）：{len(evidence)} 条\n")
    return 0

def command_guidance_context(_: argparse.Namespace) -> int:
    paths = [ROOT/'个人学习画像.md', ROOT/'方向与能力地图.md']
    items = subjects()
    paths.extend(p/'学习主页.md' for p in items if node_type(page(p)) == 'manager')
    total = 0
    print('# Learning OS 方向分析上下文')
    print('仅汇集画像、阶段、manager 路线和结构化学习证据；不把课程资料或会话文本当作掌握证明。')
    for path in paths:
        if not path.exists() or total >= 14000:
            continue
        text = path.read_text(encoding='utf-8')
        limit = min(2400, 14000-total)
        print(f'\n## {path.relative_to(ROOT)}\n{text[:limit]}')
        if len(text)>limit: print('【摘要已截断；判断前完整读取相关文件】')
        total += min(len(text), limit)
    evidence = []
    for subject in items:
        if node_type(page(subject)) == 'leaf':
            evidence.extend(evidence_records(subject))
    print('\n## 结构化学习证据')
    if not evidence:
        print('暂无。旧主页陈述可用于定位，但不能单独证明掌握。')
    else:
        for item in sorted(evidence, key=lambda x: (x['occurred_at'], str(x['path'])), reverse=True)[:40]:
            print(f"- {item['occurred_at']}｜{item['subject']}｜{item['kind']}｜{item['module']}｜{item['result']}｜{item['path'].relative_to(ROOT)}")
    return 0

def command_intake(args: argparse.Namespace) -> int:
    source = Path(args.source).expanduser().resolve()
    if not source.exists():
        print(f'资料路径不存在：{source}', file=sys.stderr); return 1
    files = [source] if source.is_file() else [p for p in source.rglob('*') if p.is_file() and not p.is_symlink() and p.resolve().is_relative_to(source) and not any(part.startswith('.') for part in p.relative_to(source).parts)]
    kinds = Counter((p.suffix.lower() or '[无扩展名]') for p in files)
    total = sum(p.stat().st_size for p in files)
    readable = sum(1 for p in files if p.suffix.lower() in {'.md','.txt','.csv','.tsv','.json','.jsonl','.yaml','.yml'})
    pdfs = [p for p in files if p.suffix.lower() == '.pdf']
    sidecars = sum(1 for p in pdfs if any(p.with_suffix(s).exists() for s in ('.md','.txt')))
    print('# Learning OS 扩展盘点（只读）\n')
    print(f'- 来源：{source}')
    print(f'- 候选名称：{args.name or source.stem}')
    print(f'- 候选父路径：{args.parent or "待根据现有节点树判断"}')
    items = subjects()
    if args.parent:
        parent = relative_subject(args.parent)
        if not parent or not parent.exists():
            print('- 父路径状态：不存在或超出 科目/ 范围')
        elif parent in items:
            print(f'- 父路径状态：已登记 {node_role(parent, items)} 节点')
        else:
            print('- 父路径状态：现有分类目录，可承载 manager 或 leaf')
    same_names = [subject_label(p) for p in items if p.name.casefold() == (args.name or source.stem).casefold()]
    print(f'- 同名正式节点：{ "，".join(same_names) if same_names else "无"}')
    print(f'- 文件：{len(files)}；总大小：{total} bytes')
    print('- 类型：' + ('，'.join(f'{key}={value}' for key,value in sorted(kinds.items())) or '空目录'))
    if files:
        print('- 文件样例：' + '，'.join(p.name for p in files[:10]))
    print(f'- 直接机器可读文本：{readable}；PDF：{len(pdfs)}；具有同名文本旁路：{sidecars}')
    print('- 本盘点只报告显式来源，不采集会话或读取其他工作区。')
    print('\n下一步（第一阶段确认）：确定课程身份、父节点、manager/leaf 角色以及是否拆分；本命令没有写入任何文件。')
    return 0

def command_maintenance(args: argparse.Namespace) -> int:
    entry = ROOT / "系统维护入口.md"
    print("# Learning OS 系统维护入口\n")
    print(entry.read_text(encoding="utf-8").rstrip())
    print("\n## 根架构规则\n")
    print((ROOT / "AGENTS.md").read_text(encoding="utf-8").rstrip())
    items = subjects()
    print("\n## 当前节点树\n")
    print("\n".join(tree_lines(items)) or "（暂无课程节点）")
    if args.parent:
        parent = relative_subject(args.parent)
        print(f"\n## 目标父路径：{args.parent}")
        if not parent or not parent.exists():
            print("状态：不存在或超出 科目/ 范围。")
        elif parent in items:
            print(f"状态：已识别为 {node_role(parent, items)} 节点。")
            print(f"主页：{parent / '学习主页.md'}")
        else:
            print("状态：目录存在，但尚未登记为课程节点；可作为分类目录，不能承担叶级学习。")
    return 0

def public_rule_routes() -> dict[str, list[Path]]:
    """The human-readable index is the only public routing manifest."""
    text = (ROOT / '规则索引.md').read_text(encoding='utf-8')
    start, end = '<!-- RULE_ROUTES_BEGIN -->', '<!-- RULE_ROUTES_END -->'
    if text.count(start) != 1 or text.count(end) != 1 or text.index(start) > text.index(end):
        raise ValueError('规则索引缺少唯一有效路由表；不能把本输出视为完整执行依据')
    routes = {'open': [], 'plan': [], 'manual': []}
    owners = set()
    for line in text.split(start)[1].split(end)[0].splitlines():
        line = line.strip()
        if not line:
            continue
        if not (line.startswith('|') and line.endswith('|')):
            raise ValueError(f'公共路由表存在非表格行或缺失边界符，不能静默忽略：{line}')
        columns = [s.strip() for s in line[1:-1].split('|')]
        if len(columns) != 3:
            raise ValueError('公共路由必须有三列：触发条件、源文件、CLI场景')
        if columns == ['何时读取', '唯一维护源', 'CLI读取场景']:
            continue
        if all(re.fullmatch(r':?-{3,}:?', c) for c in columns):
            continue
        if not columns[0] or re.fullmatch(r':?-{3,}:?', columns[0]):
            raise ValueError(f'公共路由触发条件为空或分隔行损坏：{line}')
        scenes = [s.strip() for s in columns[2].split(',')]
        links = re.findall(r'\]\(([^)]+)\)', columns[1])
        if not links or len(scenes) != len(set(scenes)) or any(s not in routes for s in scenes):
            raise ValueError(f'公共路由无效：{line}')
        for link in links:
            path = (ROOT / link).resolve()
            if path.parent != ROOT.resolve() or path.suffix != '.md' or '#' in link:
                raise ValueError(f'公共规则须引用根目录完整Markdown：{link}')
            if path in owners:
                raise ValueError(f'公共规则重复登记：{link}')
            owners.add(path)
            for scene in scenes:
                routes[scene].append(path)
    if not routes['open'] or not routes['plan']:
        raise ValueError('公共索引缺少open或plan路由')
    return routes

def print_learning_rules(subject: Path, *, planning: bool = False) -> bool:
    """Read current indexed rules in full; never fall back to an old list."""
    try:
        paths = [ROOT / '规则索引.md'] + public_rule_routes()['plan' if planning else 'open']
    except (OSError, ValueError) as exc:
        print(f'【缺少规则入口或路由无效：{exc}；请读取公共规则索引，不能把本输出视为完整执行依据】')
        return False
    paths += [subject / name for name in ('AGENTS.md', '规则索引.md', '学习方式与交接.md')]
    complete = True
    for path in paths:
        if path.exists():
            print(f'\n## {path}\n{path.read_text(encoding="utf-8").rstrip()}')
        elif path.name != '学习方式与交接.md':
            print(f'\n【缺少规则入口：{path}；不能把本输出视为完整执行依据】')
            complete = False
    return complete

def command_open(args: argparse.Namespace) -> int:
    if not args.query:
        return command_brief(args)
    exact = relative_subject(args.query)
    registered = subjects()
    if exact and exact.exists() and exact not in registered:
        print(f"“{args.query}”是普通分类目录，不是学习入口；请改开其最近的正式 manager 节点。")
        return 1
    subject = resolve(args.query)
    if not subject:
        candidates = resolve_candidates(args.query)
        if len(candidates) > 1:
            print(f"“{args.query}”同时匹配多个正式节点，请改用完整路径指定其一：")
            for candidate in candidates:
                print(f"  - {subject_label(candidate)}")
            return 1
        print(f"没有找到“{args.query}”对应的正式节点。只能打开同时包含 AGENTS.md 和 学习主页.md 的 manager 或 leaf；普通分类目录请改开最近的 manager。")
        return 1
    print(f"# 已进入：{subject_label(subject)}\n")
    if node_role(subject, registered) == "leaf":
        if not print_learning_rules(subject):
            return 1
    else:
        startup = ROOT / '节点启动协议.md'
        if not startup.is_file():
            print(f'【缺少节点启动协议：{startup}；不能把本输出视为完整执行依据】')
            return 1
        print(f'## {startup}\n{startup.read_text(encoding="utf-8").rstrip()}\n')
        print("## 共同学习偏好\n")
        print(PREFERENCES.read_text(encoding="utf-8").rstrip(), "\n")
        print("## 本科目规则\n")
        print((subject / "AGENTS.md").read_text(encoding="utf-8").rstrip(), "\n")
    print("## 学习主页\n")
    print(page(subject).rstrip())
    for source in continuation_files(subject):
        print(f'\n## 续学来源：{source.name}（核对模块；片段不是进度结论）\n')
        print(source.read_text(encoding='utf-8')[:6000])
    if node_role(subject, registered) == "leaf":
        print('\n下一步读取主页指定的当前模块、原题清单和相关交接；本命令未核定任何题目完成，也不按最大模块编号续排。')
    return 0

def command_plan_context(args):
    subject = resolve(args.query) if args.query else leaf_subject_for_cwd()
    if not subject or node_type(page(subject)) != 'leaf':
        print('请在叶节点运行，或指定唯一科目完整路径。'); return 1
    if not print_learning_rules(subject, planning=True):
        return 1
    paths = [subject / '规划导航.md', subject / '学习主页.md']
    paths += [subject / name for name in ('长期路线.md', '长期学习路线.md')]
    paths += continuation_files(subject)
    total = 0
    for path in paths:
        if not path.exists(): continue
        value = path.read_text(encoding='utf-8')
        limit = min(3500, max(0, 10000-total))
        print(f'\n## {path}\n{value[:limit]}')
        if len(value) > limit: print(f'【资料摘要已截断；执行前须完整读取相关文件：{path}】')
        total += min(len(value), limit)
    print('\n接下来按主页定位当前模块、原题清单和最近交接，核准内容与题目两部分；partial交接先接剩余任务，不按文件名最大值推断已完成。本命令未读取原题或确认完成，相关模块、清单和原题区仍须读取。')
    return 0

def node_startup_entry(subject: Path, role: str) -> str:
    """Short identity and links only; shared startup semantics stay in Markdown."""
    link = os.path.relpath(ROOT / '节点启动协议.md', subject).replace(os.sep, '/')
    root_entry = os.path.relpath(ROOT / 'AGENTS.md', subject).replace(os.sep, '/')
    return (f'先读取根入口 {root_entry}，不依赖祖先自动加载。\n\n## 本节点启动\n\n本节点：`{subject_label(subject)}`（`{role}`）。'
            '具体职责、启用状态与当前任务见本文件及 [学习主页](学习主页.md)。'
            f'每次新对话先执行 [节点启动协议]({link})，不依赖接续提示词。\n\n')

def create_node(args: argparse.Namespace) -> int:
    name = args.name.strip()
    if not name or name in {".", ".."} or "/" in name or "\\" in name or name.startswith("."):
        print("科目名称不能为空，也不能包含路径字符。")
        return 1
    if not args.parent or args.role not in NODE_TYPES:
        print("新建课程必须显式提供 --parent 和 --role manager|leaf；先完成课程层级判断。")
        return 1
    parent = relative_subject(args.parent)
    if not parent or not parent.exists() or not parent.is_dir():
        print("父路径不存在，或超出 科目/ 范围。")
        return 1
    existing = subjects()
    if parent in existing and node_role(parent, existing) != "manager":
        print("叶节点不能作为新课程的父节点；请先选择总管节点或分类目录。")
        return 1
    target = parent / name
    if any(p in parent.parents and node_type(page(p)) == 'leaf' for p in existing):
        print('父路径位于已有叶节点内部，不能创建嵌套课程。'); return 1
    if target.exists() and not (getattr(args, 'reserved_target', None) == target and not any(target.iterdir())):
        print(f"科目已经存在：{target}")
        return 1

    if args.role == "manager":
        agent_text = f"""# {name}总管

{node_startup_entry(target, 'manager')}## 节点角色

本目录是 `manager` 总管，负责子课程地图、长期协调、跨叶节点总结和综合练习，不直接承载日常教学模块或本科目 Anki。

## 总管任务例外

- 单科日常学习、单题讲解和单科记录进入对应叶节点。
- 整卷、综合练习、跨叶复盘和跨科调度可以留在本总管。
- 开始综合任务时一次性确认任务范围、允许读取的子节点和产物位置；综合产物写入本总管的 `练习/`，具体修订回写对应叶节点。

## 维护入口

进行扩展、拆分或修改前，先读取 [系统维护入口]({os.path.relpath(ROOT / '系统维护入口.md', target)})，检查父节点与候选叶节点，并在用户确认后写入。

## 记录

只保存课程地图、长期路线、交叉关系和自然语言综合总结；真正学习进入已确认的叶节点。
"""
        page_text = f"""---
node_type: manager
aliases: []
updated_at: {datetime.now().astimezone().date().isoformat()}
---

# {name}

## 当前进度

总管节点已建立，子课程和第一条叶级学习主线尚待确认。

## 我喜欢的学习方式

遵循根目录学习偏好；本层负责协调，不直接替代叶节点教学。

## 资料入口

暂无。确认叶节点后从叶节点资料入口进入。

## 最近形成的理解

暂无。

## 接下来可以做什么

- 先整理候选叶节点、先修关系和主线方案，再确认后创建叶节点。
"""
        atomic_write(target / "AGENTS.md", agent_text)
        atomic_write(target / "学习主页.md", page_text)
        atomic_write(target / "课程地图.md", f"# {name}｜课程地图\n\n候选子课程待维护入口确认后补充。\n")
        print(f"已创建总管节点：{target}")
        return 0

    agent_text = f'''# {name}智能体

{node_startup_entry(target, 'leaf')}先读 [本科规则索引](规则索引.md)，按任务读取公共规则。只在本叶节点工作，不扫描兄弟科目。

## 本科差异

主线及材料由学习主页和当前模块指定；尚未确定时只定位，不凭空生成全课路线。
'''
    page_text = f"""---
node_type: leaf
aliases: []
updated_at: {datetime.now().astimezone().date().isoformat()}
---

# {name}

## 当前进度

尚未正式开始；可以直接从用户当前提出的问题或材料进入。

## 学习主线

- 主线类型：待维护（视频主线 / 教材主线 / 题目或考纲主线 / 项目主线 / 材料/能力主线）
- 课程状态：未开始
- 当前阶段：等待定位

## 我喜欢的学习方式

遵循根目录学习偏好；有需要时再补充本科目的具体互动方式。

## 资料入口

暂无。新资料直接放入 `资料/`，无需预先建立完整书目。

## 最近形成的理解

暂无。

## 接下来可以做什么

- 从当前最感兴趣的一个问题、章节或材料开始。

这只是选择。
"""
    atomic_write(target / "AGENTS.md", agent_text)
    atomic_write(target / "学习主页.md", page_text)
    root_link = os.path.relpath(ROOT, target).replace(os.sep, '/')
    index = f'# 本科规则索引\n\n- [公共规则索引]({root_link}/规则索引.md)：按任务读取。\n- [学习主页](学习主页.md)：材料和进度。\n- [规划导航](规划导航.md)：本科下一模块边界。\n'
    index += f'- [Anki公共流程]({root_link}/Anki制卡与导入协议.md)：模块收尾读取；未配置时不自动启用。\n'
    atomic_write(target / '规则索引.md', index)
    atomic_write(target / '规划导航.md', '# 本科规划导航\n\n主线尚待确认，沿主页指定的课程或教材定位。维护时只补本科阶段、必要前置、切分建议和可观察产物；共性细则见 [规则索引](规则索引.md)，不复制规则正文。\n')
    directory_text = {
        '资料': '# 资料\n\n用到时再添加内容；无需为了目录完整提前生成文件。资料存在不等于已经学习。\n',
        '学习记录': '# 学习记录\n\n只保存有延续价值的记录。模块交接按根目录 `模块切换协议.md` 的“学习证据格式” 添加最小元数据。\n',
        '练习': '# 练习\n\n保存用户真实作答及必要复盘；可计入跨科总览的作答按根目录 `模块切换协议.md` 的“学习证据格式” 添加最小元数据。\n',
    }
    for directory, content in directory_text.items():
        atomic_write(target / directory / "README.md", content)
    print(f"已创建轻量科目：{target}")
    print("已创建主页、规则索引、本科导航和三个轻量资料目录。")
    return 0


def command_new(args):
    # Explicit creation only; no overwrite, no traversal, no implicit roles.
    name = args.name.strip()
    if not name or name.startswith('.') or re.search(r'[\\/:*?"<>|\x00-\x1f]', name):
        raise ValueError('Invalid node name.')
    if name.endswith('.') or name.upper().split('.')[0] in {
        'CON', 'PRN', 'AUX', 'NUL', *(f'COM{i}' for i in range(1, 10)),
        *(f'LPT{i}' for i in range(1, 10)),
    }:
        raise ValueError('Node name is not portable across supported filesystems.')
    if not args.parent or args.role not in NODE_TYPES:
        raise ValueError('Specify --parent and --role explicitly.')
    parent = relative_subject(args.parent)
    if not parent or not parent.is_dir():
        raise ValueError('Parent must exist inside 科目/.')
    items = subjects()
    if any(node_type(page(p)) == 'leaf' and (p == parent or p in parent.parents) for p in items):
        raise ValueError('A leaf cannot contain another course.')
    target = parent / name
    if target.exists():
        raise ValueError('Node exists; never overwrite it.')
    raw_parent = SUBJECTS / args.parent
    for path in [raw_parent, *raw_parent.parents]:
        if path.is_symlink():
            raise ValueError('Symlink parents are not allowed.')
        if path == ROOT:
            break
    names = ['AGENTS.md', 'CLAUDE.md', '学习主页.md']
    names += ['课程地图.md'] if args.role == 'manager' else [
        '规则索引.md', '规划导航.md', '资料/README.md', '学习记录/README.md', '练习/README.md']
    print('Planned new node: ' + str(target.relative_to(ROOT)))
    print('\n'.join(names))
    if not args.apply:
        print('Dry run: no files written. Confirm this list before adding --apply.')
        return 0
    # Reserve the new directory exclusively before the source generator writes.
    target.mkdir(exist_ok=False, mode=0o700)
    # Source generator checks existence itself, so supply a reserved empty target
    # through an explicit parameter rather than remove/recreate the directory.
    args.reserved_target = target
    result = create_node(args)
    if result == 0:
        atomic_write(target / 'CLAUDE.md', '@AGENTS.md\n')
    return result


def command_doctor(_):
    errors = []
    try:
        routes = public_rule_routes()
        for path in {p for values in routes.values() for p in values}:
            if not path.is_file():
                errors.append('Missing indexed rule: ' + path.name)
    except (OSError, ValueError) as exc:
        errors.append(str(exc))
    required = ['AGENTS.md', 'CLAUDE.md', '规则索引.md', '科目/README.md', '个人学习画像.md']
    for relative in required:
        if not (ROOT / relative).is_file():
            errors.append('Missing: ' + relative)
    items = subjects()
    surfaces = list(ROOT.glob('*.md'))
    for subject in items:
        role = node_type(page(subject))
        if role not in NODE_TYPES:
            errors.append('Invalid node role: ' + subject_label(subject))
        parent = nearest_registered_parent(subject, items)
        if parent and node_type(page(parent)) == 'leaf':
            errors.append('Leaf contains node: ' + subject_label(subject))
        if role == 'manager' and any((subject / p).exists() for p in ['模块', 'Anki']):
            errors.append('Manager contains leaf-only module or Anki directory.')
        for name in ['AGENTS.md', 'CLAUDE.md', '学习主页.md'] + (
                ['规则索引.md', '规划导航.md'] if role == 'leaf' else ['课程地图.md']):
            if not (subject / name).is_file():
                errors.append('Missing node file: ' + subject_label(subject) + '/' + name)
        surfaces.extend(subject.glob('*.md'))
        surfaces.extend((subject / '模块').glob('*.md'))
    for path in surfaces:
        if path.is_symlink():
            errors.append('Symlink surface refused: ' + str(path.relative_to(ROOT)))
            continue
        for link in broken_local_links(path):
            errors.append(str(path.relative_to(ROOT)) + ': missing local link ' + link)
        for link in broken_anchors(path):
            errors.append(str(path.relative_to(ROOT)) + ': missing anchor ' + link)
    for error in errors:
        print('ERROR: ' + error)
    print(f'Checked {len(items)} nodes and rule links; errors: {len(errors)}.')
    print('Structure checks do not prove material coverage, answers, learning or Anki import.')
    return int(bool(errors))


def command_checkpoint(args):
    subject = resolve(args.query) if args.query else leaf_subject_for_cwd()
    if not subject or node_type(page(subject)) != 'leaf':
        raise ValueError('Select one leaf for a checkpoint.')
    path = subject / '续学位置.md'
    if path.is_symlink():
        raise ValueError('Checkpoint symlinks are refused; no target read or changed.')
    def revision():
        return hashlib.sha256(path.read_bytes()).hexdigest() if path.exists() else 'absent'
    if args.inspect:
        print(json.dumps({'expected': revision()}, ensure_ascii=False))
        return 0
    if not args.expected or not args.text or len(args.text) > 1600:
        raise ValueError('Inspect first, then supply --expected and a short --text.')
    lock = subject / '.checkpoint.lock'
    fd = os.open(lock, os.O_CREAT | os.O_EXCL | os.O_WRONLY, 0o600)
    try:
        if revision() != args.expected:
            raise ValueError('Revision conflict; existing checkpoint kept. Inspect before retrying.')
        value = ('---\nkind: lightweight_checkpoint\n'
                 f'subject: {subject_label(subject)}\n'
                 f'module: {json.dumps(args.module, ensure_ascii=False)}\n'
                 f'phase: {"closed" if args.closed else "active"}\n---\n\n'
                 '# 续学位置\n\n' + args.text.strip() + '\n')
        atomic_write(path, value)
        if path.read_text(encoding='utf-8') != value:
            raise ValueError('Saved checkpoint not confirmed; inspect before retrying.')
    finally:
        os.close(fd)
        lock.unlink()
    print('Saved and read back: ' + str(path.relative_to(ROOT)))
    return 0


def build_parser():
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest='command', required=True)
    for name, func in [('status', command_status), ('doctor', command_doctor),
                       ('guidance-context', command_guidance_context)]:
        sub.add_parser(name).set_defaults(func=func)
    for name, func in [('brief', command_brief), ('overview', command_overview),
                       ('open', command_open), ('plan-context', command_plan_context)]:
        child = sub.add_parser(name)
        child.add_argument('query', nargs='?')
        child.set_defaults(func=func)
    for name, func in [('intake', command_intake), ('maintenance', command_maintenance)]:
        child = sub.add_parser(name)
        child.add_argument('--parent')
        if name == 'intake':
            child.add_argument('source')
            child.add_argument('--name')
        child.set_defaults(func=func)
    child = sub.add_parser('new')
    child.add_argument('name')
    child.add_argument('--parent', required=True)
    child.add_argument('--role', choices=sorted(NODE_TYPES), required=True)
    child.add_argument('--apply', action='store_true')
    child.set_defaults(func=command_new)
    child = sub.add_parser('checkpoint')
    child.add_argument('query', nargs='?')
    child.add_argument('--inspect', action='store_true')
    child.add_argument('--expected')
    child.add_argument('--text')
    child.add_argument('--module', default='模块内')
    child.add_argument('--closed', action='store_true')
    child.set_defaults(func=command_checkpoint)
    return parser


def main():
    try:
        marker = json.loads((ROOT / 'workspace.json').read_text(encoding='utf-8'))
        if marker.get('schema_version') != 1 or marker.get('status') != 'initialized':
            raise ValueError('Not an initialized private workspace.')
        args = build_parser().parse_args()
        return int(args.func(args))
    except (OSError, ValueError) as exc:
        print('Learning OS stopped: ' + str(exc), file=sys.stderr)
        return 1


if __name__ == '__main__':
    raise SystemExit(main())
